# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9.7"]

    steps:
    - uses: actions/checkout@v2
#    - uses: nanasess/setup-chromedriver@master

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install libxss1 libappindicator1 libindicator7 python3-pip make git xvfb wget curl -y
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome*.deb
        pip3 install --user -r requirements.txt
        
    - name: Try to run
      env:
        HEADLESS: 1
      run: |
        cd scrapper && ./main.py & curl -s -d '{"id":0, "method":"cars.list", "params":{"brand":"Opel", "model":"Vectra", "price_to":20000, "page":1}, "jsonrpc":"2.0"}' http://localhost:8090 && pkill main.py
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Test with pytest
#       run: |
#         pytest
